# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/51434309-99d3-40bb-b6ad-7b7c724e0ab8";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B503-950E";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7ed3ce23-326d-40f9-bb77-4518553e4ba0"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-2899f9df7835.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-6dd5656163e4.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-8b924b38a1a5.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-9899c7649305.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-ada6f6ba45a4.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-c8372fc9308f.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth89f7b07.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9e99185.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethdcdbd2a.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf7f6736.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
